CREATE TABLE CLIENT(
  ID BIGINT PRIMARY KEY NOT NULL IDENTITY,
  NAME VARCHAR(50) NOT NULL,
  PASSWORD VARCHAR(50) NOT NULL,
  PHONE VARCHAR(50) NOT NULL,
  EMAIL VARCHAR(50) NOT NULL,

);

CREATE TABLE ITEM(
  ID BIGINT PRIMARY KEY NOT NULL IDENTITY,
  TITLE VARCHAR(50) NOT NULL,
  DETAILS VARCHAR(50) NOT NULL,
  POSTALCODE INT NOT NULL,
  PICKUPDATE VARCHAR(50) NOT NULL,
  PHOTO VARCHAR(MAX) NOT NULL,

);

